tcptomato/ROad-Block

road-block-filters.txt

block pop-up banner antena play

Popup banner antena play

---

road-block-filters.txt

In dreapta pe site apar 2 bannere la alte servicii de alte lor.

Added block for digi24.ro right sidebar

---

road-block-filters.txt

Sort by name

---

road-block-filters.txt

Blocare popup pe www.academiacatavencu.info

www.academiacatavencu.info - Popup block

---

road-block-filters.txt

Domenii malitioase de spam prin email.

Spam nesletter

---

road-block-filters.txt

lista actualizata, va continua ...

Spam newsletter filters update

---

road-block-filters.txt

These are 2 popular sites from my area.

Block ads for Cluj local sites

---

road-block-filters-light.txt
road-block-filters.txt

Am eliminat „www.”-urile reduntante + listele sunt similare 100% (erau câteva linii lipsă care într-un filtru figurau, în celălalt nu).
Practic liniile ambelor filtre trebuie să fie similare până la „@@||prosport.ro/embed/$first-party,inline-script”.

Update both filters

---

road-block-filters-light.txt
road-block-filters.txt

În comiterea din 12 februarie am uitat să reintroduc 3 linii care figurau înainte + am adăugat filtre noi pentru site-uri din Satu Mare. :)

New filters + re-added few lines

---

road-block-filters-light.txt
road-block-filters.txt

Un filtru crăpa articole pe un site + blocată o nouă reclamă pe alt site-uleț.

Little fix + new filter

---

road-block-filters-light.txt
road-block-filters.txt

- Elementele specifice listei full au fost mutate din josul listei în susul listei (exista tendința ca filtre noi să fie puse la capătul listei, filtre care nu aveau treabă neapărat cu elementele listei full și ducea la confuzie)
- Am ordonat puțin ambele liste, ca să fie uniforme (singura diferență acum este că pentru lista full filtrele specifice sunt amplasate sus, în rest fiind totul similar cu lista light)
- Filtre actualizate pentru Satu Mare + Antena3

Updates for ROad-Block Full & Light

---

road-block-filters-light.txt
road-block-filters.txt
road-kill-filters.txt

- Am adăugat un filtru nou la Antena3 + modificări la filtrele de Satu Mare
- Nu știam că există și un fișier separat doar pentru roadkill, l-am modificat acum și pe ăla și e adus la zi cu ce este în full & light.

Update full, light & roadkill

---

road-block-filters-light.txt

addresses unhidden stuff from `https://www.lauralaurentiu.ro/retete-culinare/supe-ciorbe/ciorba-de-burta.html`

lauralaurentiu. ro

---

road-block-filters-light.txt

Addressed spaces on `https://www.shtiu.ro/chitare-sau-chitari-cum-este-corect-121547.html`

adds cosmetic filter

---

road-block-filters-light.txt

the filters which were added in this PR were tested on `https://www.odat.ro/cele-mai-proaste-masini-second-hand-dar-si-cele-mai-bune/`

odat.ro ads and space

---

road-block-filters-light.txt

this PR contains a commit which has a filter which hides one or more elements on 
`https://www.kudika.ro/articol/wellness/68854/ce-analize-se-fac-pentru-circulatia-sangelui.html`

cosmetic filter

---

road-block-filters-light.txt

should address space on `https://www.impact.ro/el-a-fost-prima-mare-dragoste-a-simonei-halep-andrei-e-casatorit-si-are-doi-copii-417902.html`

update impact. ro

---

road-block-filters-light.txt

`https://antenastars.ro/star-news/ioana-popescu-sia-pierdut-rucsacul-cu-bani-si-filmari-interzise-id102476.html` - anti-adblocking played instead of video

update - "antena"

---

road-ubo.txt

"str" : `https://www.cool-etv.net/` => "Ant 3" [`||www.cool-etv.net/menu/ebab_mb5czm_ico_10.png` in uBO selector should highlight] "S1" => `https://www.cool-etv.net/ch/an3.htm` [+ whatever may get added]

cool-etv. net - fixes going to the last page

---

road-block-filters-light.txt

`https://www.divahair.ro/vedete`

update divahair. ro

---

road-block-filters-light.txt

Filters were tested on `https://ziarulargesul.ro/

ziarulargesul. ro - ads, html element

---

road-block-filters-light.txt

First filter was tested on `https://voceavalcii.ro/social/angajatii-din-valcea-au-cele-mai-mici-salarii-din-tara/`

vocealvalcii.ro, gazetadambovitei.ro - advertising

---

road-block-filters-light.txt

`https://www.monitoruldevrancea.ro/2022/09/13/observator-astronomic-la-odobesti/`
https://user-images.githubusercontent.com/113248817/190175322-6433b98f-c539-4a20-b1cf-39d0d9236577.png
https://user-images.githubusercontent.com/113248817/190175514-3f5b4ca2-d3d0-4265-bff7-1d066b30151d.png
https://user-images.githubusercontent.com/113248817/190175733-59d96d23-2a2f-4e1b-a5dc-b55623df594e.png
---
`https://www.monitoruldevrancea.ro/`
`monitoruldevrancea.ro##[class*="td-a-rec-id-custom_ad"]`
https://user-images.githubusercontent.com/113248817/190175945-d0e74e17-f02a-4c34-8527-d3661e7a36fb.png
`||monitoruldevrancea.ro/*reclama`
https://user-images.githubusercontent.com/113248817/190176277-c1823d5f-78c4-4ddd-8633-67ba4c6b4fe2.png

monitorulvrancea.ro - ads, DOM elements

---

road-block-filters-light.txt

gorjonline.ro - ad

---

road-block-filters-light.txt

`https://www.newmoney.ro/cum-a-accelerat-businessul-glovo-in-romania-in-perioada-pandemiei-covid-19/?utm_source=WALL-STREET+%5B2%5D&utm_medium=website&utm_campaign=fidmee`
`||newmoney.ro/*Banner$image`
Possibly hidden by `newmoney.ro#?#.sow-image-container:-abp-has([target="_blank"][rel])`
---
`newmoney.ro#?#.sow-image-container:-abp-has([target="_blank"][rel])`
`https://www.newmoney.ro/`

newmoney.ro - ads

---

road-block-filters-light.txt

`https://cespun.eu/meme-uri-amuzante/`

cespun.eu - space

---

road-block-filters-light.txt

https://user-images.githubusercontent.com/113248817/190716963-e795618d-5332-42aa-b3f7-0b14b0e634b0.png

dinpopor. ro DOM element

---

road-block-filters-light.txt

`https://www.myexpert.ro/`
https://user-images.githubusercontent.com/113248817/190876809-fdd9450f-b6bf-42d6-b162-e050061f07f3.png
https://user-images.githubusercontent.com/113248817/190876839-0d58588c-3025-477b-a4d3-8a4b0729485b.png

myexpert.ro - ads, DOM/HTML element

---

road-block-filters-light.txt

`https://parerimagazin.ro/pareri/fashion-book-ro/`

parerimagazin. ro element

---

road-block-filters-light.txt

to address advertising and DIV stuff, to the right of content
https://user-images.githubusercontent.com/113248817/191561394-46ac27c4-9e30-4536-81fb-58f185c0a05c.png

newsbv.ro - ads + DIV stuff

---

road-block-filters-light.txt

`https://www.nasul.tv/`
`nasul.tv#?#.wpb_wrapper:-abp-has([href^="https://repigmentare.ro/"])`
</details>

update nasul. tv

---

road-block-filters-light.txt

`https://www.libertateapentrufemei.ro/`
</details>

libertateapentrufemei. ro - DIV element

---

road-ubo.txt

`https://www.acasatv.ro/`
</details>

acasatv.ro - DIV stuff

---

road-block-filters-light.txt

`https://www.stirilekanald.ro/`
</details>

update kanald. ro / stirilekanald. ro

---

road-block-filters-light.txt

`https://www.fanatik.ro/`
`fanatik.ro##[data-banner]` - `https://www.fanatik.ro/stiri-mondene`

update fanatik. ro

---

road-block-filters-light.txt

seemingly redundant/obsolete filters

update informatia-zilei. ro

---

road-block-filters-light.txt

`https://www.gedave.ro/top-5-motive-pentru-care-sa-citesti-constant-stiri-mondene/`
<details><summary>screenshots</summary>
</details>

gedave. ro - ads

---

road-block-filters-light.txt

`https://stiri.md/story/business`
<details><summary>screenshots</summary>
</details>

stiri. md DIV elements

---

road-block-filters-light.txt

`https://www.gsp.ro/`
<details><summary>Screenshots:</summary>
</details>
There is also advertising for mogyi
<details><summary>Screenshots:</summary>
</details>

gsp. ro - ad

---

road-block-filters-light.txt

`https://ziare.com/panouri-fotovoltaice/instalatie-fotovoltaica-productie-anuala-roman-experienta-1775097`
`ziare.com/images/3zero0-2cinci0-2.gif`

ad on ziare. com

---

road-block-filters-light.txt
road-block-filters.txt

- Update filters used for Satu Mare websites.
- `road-block-filters.txt` is basically `road-kill-filters.txt` + `road-block-filters-light.txt`.
Some ppl might still use `road-block-filters.txt` in their adblockers.

Update SM filters + Update road-block-filters.txt

---

road-block-filters-light.txt

Space on `https://dexonline.net/` between search bar and paragraph
Ad on `https://dexonline.net/definitie-masina`

dexonline.net - space & ad

---

road-block-filters-light.txt

Web page: `https://www.actualitateavranceana.ro/indicii-robor-continua-sa-scada/`
<details><summary> Screenshots: </summary>
</details>

actualitateavranceana.ro - ads

---

road-block-filters-light.txt

`https://www.romedic.ro/cauta.php?q=febra&x=16&y=3`
<details><summary> Screenshot: </summary>
</details>

romedic.ro - element

---

road-block-filters-light.txt

**URL**= NSFW
```
https://filmeporno.me/niciodata-nu-a-primit-doua-puli-in-fund-in-acelas-timp-aceasta-bruneta-perversa/
https://filmexxx18.com/44226/
```
**ISSUE**= Popups in new tab 
described here `https://forums.lanik.us/viewtopic.php?t=48324`
Ublock origin stable, firefox stable

address https://forums.lanik.us/viewtopic.php?t=48324

---

road-ubo.txt

**URL**=
`https://veziseriale.org/episoade/get-gotti-sezonul-1-episodul-2/`
**ISSUE**=
antiadb in netu player ,described here `https://www.reddit.com/r/uBlockOrigin/s/1vmt77G9tz`
Ublock origin, firefox/opera stable

address https://www.reddit.com/r/uBlockOrigin/s/WiKvpUQJzH

---

road-block-filters-light.txt

rotating ads under navigation buttons (for either kekshost / freakhosting)

upd sa-mp.ro

---

road-block-filters-light.txt

`https://www.ziarpiatraneamt.ro/`
ads in right sidebar

upd ziarpiatraneamt.ro

---

road-block-filters-light.txt

ads in right sidebar (may need to scroll down to see them)

upd stiri-neamt.ro

---

road-block-filters-light.txt

`https://tvmneamt.ro/`
`https://tvmneamt.ro/peste-900-de-locuri-de-munca-disponibile-in-neamt-prin-ajofm-la-sfarsitul-lunii-noiembrie/`
ads in right sidebar

upd tvmneamt.ro

---

road-block-filters-light.txt

`https://informatia-zilei.ro/romania-pandita-de-pericolul-spiralei-salarii-pret/`
ad under article
I disabled all other filters on my side; I haven't found any other ad

upd informatia-zilei.ro

---

road-ubo.txt

described https://github.com/uBlockOrigin/uAssets/issues/21915

fix https://github.com/uBlockOrigin/uAssets/issues/21915

---

road-block-filters-light.txt

ads + placeholders on `https://www.loganclub.ro/forum/`
ads on `https://www.clubmercedes.ro/`

car club sites - ads

---

road-block-filters-light.txt

`https://forum.b-zone.ro/`
ad in right sidebar

forum.b-zone.ro - ad

---

road-block-filters-light.txt

hostclub.ro seems to no longer work

they shut down

---

road-block-filters-light.txt

`https://rangfort.ro/forum/` - ad in right sidebar (for HZone)

upd https://rangfort.ro/forum/

---

road-block-filters-light.txt

`https://ziare.com/preturi-apartamente-bucuresti/imobiliare-2024-apartamente-ieftine-1880369`
placeholders between paragraphs

ziare.com - placeholders

---

road-ubo.txt

antiadb annoyance comes with each refresh

https://github.com/AdguardTeam/AdguardFilters/issues/183110

---

road-block-filters-light.txt

redirects to invalid discord invite link

No longer needed

---

road-block-filters-light.txt

block captain morgan ad on gsp.ro

---

road-block-filters-light.txt

upd arenait.ro

---

road-ubo.txt

`https://www.tvonline123.com/tvlive/?url=tvr1-hd`
Server 1

tvonline123.com stream player anti-adblock

---

road-block-filters-light.txt

focuspress.ro ads

---

road-block-filters-light.txt

`https://bonapetit.ro/reteta/dovlecei-pane/`
ad (*2) for trafic.ro
Was thinking about opening PR in EasyList for the plugin, but not sure about all use cases

bonapetit.ro

---

road-block-filters-light.txt

`https://www.jurnaldevrancea.ro/`

jurnaldevrancea.ro ads

---

road-block-filters-light.txt

`https://observatorconstanta.ro/`

observatorconstanta.ro - ads

---

road-block-filters-light.txt

`https://servuspress.ro/caravana-sarbatori-cu-sanatate-ajunge-la-soimus-testari-gratuite-pentru-locuitori_285522.html`

servuspress.ro right sidebar ads

---

road-block-filters-light.txt

obiectiv.net right sidebar ads

---

road-block-filters-light.txt

`https://www.wowbiz.ro/mama-lui-nu-stie-ca-a-murit-parintii-lui-armando-tanarul-mort-in-accidentul-cumplit-din-ploiesti-se-intorc-de-urgenta-in-romania-ies-la-iveala-noi-imagini-din-ziua-tragediei-ce-a-facut-soferul-cu-cateva-momente-inainte-de-impactul-violent-20445938`
`https://www.kanald.ro/kanal-d-a-primit-distinctia-de-excelenta-in-media-la-gala-financial-intelligence-awards-20445700`
`https://kanald2.ro/culita-sterp-si-daniela-iliescu-au-ales-numele-fetitei-anuntul-a-fost-facut-chiar-de-sotia-artistului-20445376`
https://github.com/user-attachments/assets/17017145-d9e3-48a8-8560-30f94a24344a
it's basically a placeholder -> no adblocker => adsense ad

kanald placeholders

---

road-ubo.txt

`https://kanald2.ro/video-misterul-sferei-luminoase-de-pe-litoral-despre-ce-este-vorba-de-fapt-20445662`
possible cookie issues

kanald2.ro anti-adb

---

road-block-filters-light.txt

punctul.ro ads

---

road-block-filters-light.txt
road-block-filters.txt
road-ubo.txt

Domain "science.hotnews.ro" redirected to "hotnews.ro/c/science" so, there's no need to have that anymore.

Added cosmetic filter on www.digi.ro & Removed one filter entry
