road-block-filters.txt
Adaugat rt.awstaticdn.net in lista de interziceri. Acest website adauga ferestre de tip pop-up in care forteza utilizatorii sa instaleze plugin-uri pentru navigatoare.
=> added rt.awstaticdn.net to blocklist

road-block-filters.txt
Se pare ca sintaxa * nu inlocuieste subdomeniile trebuiesc declarate toate.
Pana acum doar rt.awstaticdn.net si dl14.awstaticdn.net .
=> Fix awstaticdn popup block

road-block-filters-light.txt, road-block-filters.txt
Hello, Dandelion Sprout here. I learned about your lists from how we both were struggling to get uBlock Origin's developers to notice our filter lists, which in my case is about a Norwegian list. So I figured out, why don't I try to help make your list even better, so that they may one day take you (and by extension me) a lot more seriously?
I ran the two lists through https://arestwo.org/famlam/redundantRuleChecker.html, which gave the following results for the full list, which I cite verbatim:
"   Finished (after 1 second)!  17 redundant rules found!
||indeeway.ro^ has been made redundant by ||indeeway.ro^
||www.timesnewroman.ro/files/attach/images/127/598108/570x185animat2.gif has been made redundant by ||www.timesnewroman.ro/files/attach/images/127/598108/570x185animat2.gif …
=> Suggesting the removal of redundant lines

road-block-filters-light.txt, road-block-filters.txt
The **website, app and blog of bannersnack.com** is _broken_ due to the rule. I have made this **PR** to adjust the blocking **_on third party domains only_**, thus, allowing the bannersnack apps to work properly.
Affected domains:
https://www.bannersnack.com
https://app.bannersnack.com
https://blog.bannersnack.com
=> fix bannersnack.com

road-ubo.txt
After attempting to view footage from `https://posturi.live/tv/pro-tv`, there seems to be some sort of "popup" as well as something blocked by `||greatdexchange.com^$popup` (filter from EasyList)
=> posturi. live | anti-popup filter

road-block-filters-light.txt
`https://www.bursa.ro/`
On `https://www.bursa.ro/studiu-coface-pentru-primul-semestru-al-anului-mediul-antreprenorial-pierderi-de-2-7-miliarde-lei-din-cauza-insolventelor-24876746`, there seem to be 2 "ads" more towards the right -- lower side of the webpage; when I opened uBO element picker, they got hidden -- is this related with the supposed selector bug?
=> bursa.ro - ads

road-block-filters-light.txt
`https://filme-bune.biz/`
https://user-images.githubusercontent.com/113248817/190261758-d74664ab-d54a-44f3-bc9c-b4548bde28b5.png
---
`https://filme-bune.biz/amintiri-din-copilarie/`
https://user-images.githubusercontent.com/113248817/190261595-f829b663-bba7-4ea2-949d-e63875b7b87b.png
---
Also, should scriptlet be added (domain name is present in uBO's `uBlock filters` two times.)?
=> filme-bune. biz - ad

road-ubo.txt
There are these filters:
```
! https://www.reddit.com/r/uBlockOrigin/comments/x9qoen/
bloground.ro##+js(nostif, show)
```
which are present in uBlock Origin's `"uBlock filters"` and I believe `bloground.ro` is Romanian
Also, if the filter is removed from uAssets, could you announce in the reddit post?
=> https://www.reddit.com/r/uBlockOrigin/comments/x9qoen/

road-block-filters-light.txt
`https://www.antena3.ro/emisiuni/in-fata-natiunii/sorin-cimpeanu-solutii-masa-calda-scoli-elevi-copii-romania-651888.html`
depending on screen size I suppose, scrolling down may be needed in order to encounter video player
@mapx- also, uBlock Origin's `uBlock filters - Unbreak` has a filter for `antena3.ro` which seems redundat given that there is https://github.com/tcptomato/ROad-Block/blob/master/road-block-filters-light.txt#L1285
=> antena3.ro video player

road-block-filters-light.txt
`https://www.computerblog.ro/telefoane/huawei-nova-y70-a-fost-lansat-in-romania.html`
https://user-images.githubusercontent.com/113248817/190847511-7489bf7d-5481-485b-b2be-c7c5da82b882.png
`https://www.computerblog.ro/telefoane/huawei-nova-y70-a-fost-lansat-in-romania.html`
https://user-images.githubusercontent.com/113248817/190847539-19256bc6-3ebe-4cf3-9500-ebec4729544d.png
https://user-images.githubusercontent.com/113248817/190847557-aa4837e8-6395-43df-b28c-fb0399e81f21.png
=> computerblog. ro ads

road-block-filters-light.txt
`https://turdanews.net/restaurantele-si-fast-food-urile-obligate-sa-afiseze-caloriile-dar-si-ce-contin-produsele-comercializate/`
</details>
=> turdanews. net - ad

road-block-filters-light.txt
`https://damboviteanul.com/2022/09/17/dorian-popa-si-a-deschis-fast-food-si-ofera-3-000-de-saorma-gratis/`
ads more to the right and also some are more towards the bottom of the page
=> damboviteanul.com - ads

road-block-filters-light.txt
The filter was made redundant by the one which was below it.
=> Remove redundant filter

road-block-filters-light.txt
URL: `https://www.clujust.ro/a-fost-publicata-legea-care-prevede-pentru-ce-condamnari-poate-fi-exclus-din-profesie-un-avocat/`
Ad seemingly in article
`https://www.clujust.ro/wp-content/uploads/2022/10/image_6483441.jpg`
=> clujust.ro - ad

road-block-filters-light.txt
`https://newsbucuresti.ro/ultimele-zile-de-art-safari-love-edition-expozitiile-se-pot-vizita-pana-duminica-10-septembrie/`
=> ads in right sidebar
encountered while using Chrome & uBO
=> newsbucuresti.ro - ads

road-block-filters-light.txt
`https://www.autoexpert.ro/top-2022-cele-mai-fiabile-masini-second-hand-pana-in-10-000-euro/`
=> ad above title
=> ad below title
`https://www.autoexpert.ro/`
=> ad
<details> <summary> Screenshot: </summary>
</details>
I haven't seen the ad for Kia => removed the filter
=> upd autoexpert.ro

road-ubo.txt
From https://github.com/brave/adblock-lists/issues/1177
detection at `https://www.clujust.ro`
opera/ublock origin
=> address https://github.com/brave/adblock-lists/issues/1177

road-block-filters-light.txt
`https://www.economica.net/autostrada-bucurestiului-a0-3_739574.html`
- placeholder above article
- native ads under the article (idk if they're y or adnow)
=> economica. net ads, ph

road-block-filters-light.txt
`https://playtech.ro/stiri/obiceiul-dubios-pe-care-il-avea-cetateanul-turc-principalul-suspect-in-cazul-crimei-din-dambovita-detalii-ciudate-ies-la-iveala-884598`
multiple placeholders within article
=> playtech.ro placeholders

road-block-filters-light.txt
`https://zicala.ro/` 
- ads in right sidebar (scroll down) --> atlas vpn, emag, fashiondays etc
- unnecessary third-party connections
=> zicala. ro ads

road-block-filters-light.txt
`https://arenavalceana.ro/liga-a-iv-a-sezon-2023-2024-23/`
- ad near logo (to the right)
- ads in right sidebar, under the weather widget (scroll down)
`https://www.clujust.ro/muntele-basmelor-de-la-buscat-isi-deschide-portile-in-weekendul-13-14-aprilie-cel-mai-mare-balaur-din-europa/`
- ad near logo
- ad within article
=> arena valceana & clujust

road-block-filters-light.txt
hides bar with hosting company logos (above chatbox & menu bar)
hides ad for freakhosting in the right sidebar (scroll down)
=> upd cspower.ro

road-block-filters-light.txt
URL: `https://www.actualitateavranceana.ro/podul-de-la-prisaca-se-redeschide-luni-viteza-va-fi-limitata-la-10-km-h/`
ads in right sidebar
=> actualitateavranceana.ro ads

road-block-filters-light.txt
`https://turdanews.net/26-milioane-de-romani-vor-beneficia-in-luna-decembrie-de-o-noua-transa-de-250-de-lei-pentru-alimente/`
=> turdanews.net ad

road-block-filters-light.txt
`https://antena3constanta.ro/2024/12/10/nou-ovidius-clinical-hospital-este-partener-acreditat-al-uk-pi-club/`
```adblock
||antena3constanta.ro/*/*728x90px.gif$image
```
=> antena3constanta.ro ad

road-block-filters-light.txt
`https://peco-online.ro/index.php`
search bucuresti => the info is hidden
=> peco-online.ro - breakage

road-block-filters-light.txt
`https://www.presasm.ro/romania-si-bulgaria-intra-in-spatiul-schengen-de-la-1-ianuarie-2025/`
ads
```adblock
presasm.ro##.header-banner
presasm.ro##.code-block
presasm.ro##.ttpAds
```
=> upd presasm.ro

road-block-filters-light.txt
`https://transilvania365.ro/a-doua-condamnare-primita-de-aristotel-cancescu-fostul-presedinte-al-consiliului-judetean-brasov-a-fost-anulata/`
```adblock
transilvania365.ro##.td-ss-main-sidebar > aside > .wp-block-image
```
=> transilvania365.ro - ads in right sidebar

road-block-filters-light.txt
`https://obiectiv-sm.ro/`
`https://obiectiv-sm.ro/2025/03/17/trei-autoturisme-avariate-in-centru-de-tencuiala-desprinsa-de-pe-cladiri/`
ads (banners)
<details> <summary> Screenshots: </summary>
</details>
=> obiectiv-sm.ro - ads
